// <auto-generated />
using System;
using Healthcare_ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healthcare_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(HealthDbContext))]
    [Migration("20260907183157_AddingInvoiceEntity")]
    partial class AddingInvoiceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfAttendees")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(36),
                            IsDeleted = false,
                            Name = "Paracetamol",
                            Notes = "مسكن وخافض للحرارة - 500mg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1858),
                            IsDeleted = false,
                            Name = "Ibuprofen",
                            Notes = "مسكن ومضاد التهاب غير ستيرويدي"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1863),
                            IsDeleted = false,
                            Name = "Amoxicillin",
                            Notes = "مضاد حيوي من مجموعة البنسلين"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1865),
                            IsDeleted = false,
                            Name = "Azithromycin",
                            Notes = "مضاد حيوي من مجموعة الماكروليدات"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1866),
                            IsDeleted = false,
                            Name = "Ciprofloxacin",
                            Notes = "مضاد حيوي واسع المجال - فلوروكينولون"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1875),
                            IsDeleted = false,
                            Name = "Metformin",
                            Notes = "خافض لسكر الدم - لمرضى السكري النوع الثاني"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1876),
                            IsDeleted = false,
                            Name = "Insulin Glargine",
                            Notes = "أنسولين طويل المفعول"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1878),
                            IsDeleted = false,
                            Name = "Amlodipine",
                            Notes = "خافض لضغط الدم - حاصرات قنوات الكالسيوم"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1879),
                            IsDeleted = false,
                            Name = "Losartan",
                            Notes = "خافض لضغط الدم - حاصرات مستقبلات الأنجيوتنسين"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1882),
                            IsDeleted = false,
                            Name = "Atorvastatin",
                            Notes = "خافض للكوليسترول - ستاتين"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1884),
                            IsDeleted = false,
                            Name = "Omeprazole",
                            Notes = "مثبط مضخة البروتون - لقرحة المعدة والارتجاع"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1885),
                            IsDeleted = false,
                            Name = "Ranitidine",
                            Notes = "مضاد للحموضة - حاصرات H2 (الاستخدام محدود)"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1886),
                            IsDeleted = false,
                            Name = "Salbutamol",
                            Notes = " موسع للشعب الهوائية - بخاخ للربو"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1888),
                            IsDeleted = false,
                            Name = "Prednisolone",
                            Notes = "كورتيكوستيرويد مضاد للالتهاب"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1889),
                            IsDeleted = false,
                            Name = "Dexamethasone",
                            Notes = "كورتيكوستيرويد قوي المفعول"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1891),
                            IsDeleted = false,
                            Name = "Chlorpheniramine",
                            Notes = "مضاد هيستامين للحساسية"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1892),
                            IsDeleted = false,
                            Name = "Cetirizine",
                            Notes = "مضاد هيستامين من الجيل الثاني - غير منوّم"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1895),
                            IsDeleted = false,
                            Name = "Acetylsalicylic Acid (Aspirin)",
                            Notes = "مميع للدم ومسكن"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1897),
                            IsDeleted = false,
                            Name = "Clopidogrel",
                            Notes = "مضاد لتجميع الصفائح الدموية"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1898),
                            IsDeleted = false,
                            Name = "Warfarin",
                            Notes = "مضاد تخثر - يتطلب مراقبة INR"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1899),
                            IsDeleted = false,
                            Name = "Levothyroxine",
                            Notes = "هرمون الغدة الدرقية - لقصور الدرقية"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1901),
                            IsDeleted = false,
                            Name = "Metoprolol",
                            Notes = "حاصرات بيتا - لضغط الدم وقصور القلب"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1902),
                            IsDeleted = false,
                            Name = "Enalapril",
                            Notes = "مثبطات الإنزيم المحول للأنجيوتنسين"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1903),
                            IsDeleted = false,
                            Name = "Furosemide",
                            Notes = "مدرّ للبول - لاحتباس السوائل"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1904),
                            IsDeleted = false,
                            Name = "Gliclazide",
                            Notes = "خافض لسكر الدم من مجموعة السلفونيل يوريا"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1905),
                            IsDeleted = false,
                            Name = "Diazepam",
                            Notes = "مهدئ - بنزوديازيبين (يُصرف بوصفة مضبوطة)"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1907),
                            IsDeleted = false,
                            Name = "Tramadol",
                            Notes = "مسكن أفيوني متوسط القوة (يُصرف بوصفة مضبوطة)"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1908),
                            IsDeleted = false,
                            Name = "Gentamicin",
                            Notes = "مضاد حيوي أمينوغليكوزيد - للحقن"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1909),
                            IsDeleted = false,
                            Name = "Clotrimazole",
                            Notes = "مضاد فطري موضعي"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 9, 7, 18, 31, 56, 400, DateTimeKind.Utc).AddTicks(1910),
                            IsDeleted = false,
                            Name = "ORS (Oral Rehydration Salts)",
                            Notes = "أملاح الإماهة الفموية - للجفاف"
                        });
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dentistry"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gynecology and Obstetrics"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Urology"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pulmonology"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Endocrinology"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Nephrology"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Otolaryngology (ENT)"
                        },
                        new
                        {
                            Id = 17,
                            Name = "General Surgery"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Family Medicine"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Emergency Medicine"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Anesthesiology"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Rheumatology"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hematology"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Infectious Diseases"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Allergy and Immunology"
                        });
                });

            modelBuilder.Entity("PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Healthcare_ERP.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Healthcare_ERP.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("Healthcare_ERP.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Healthcare_ERP.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Healthcare_ERP.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PrescriptionItem", b =>
                {
                    b.HasOne("Healthcare_ERP.Domain.Entities.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Healthcare_ERP.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Healthcare_ERP.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
